# Generated by Django 5.1.1 on 2024-10-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guest_delete_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, height_field='img_height', null=True, upload_to='', width_field='img_height'),
        ),
    ]
