# Generated by Django 5.1.1 on 2024-10-19 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_image_alter_user_uuid'),
        ('core', '0004_alter_board_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='card',
            name='board_id',
            field=models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.CASCADE, to='core.board'),
        ),
        migrations.AlterField(
            model_name='card',
            name='column_id',
            field=models.ForeignKey(db_column='column_id', on_delete=django.db.models.deletion.CASCADE, to='core.column'),
        ),
        migrations.AlterField(
            model_name='column',
            name='board_id',
            field=models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.CASCADE, to='core.board'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='board_id',
            field=models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.CASCADE, to='core.board'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
