# Generated by Django 5.0.6 on 2024-10-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_board_owner_alter_card_board_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(default='#808080', max_length=7),
        ),
        migrations.AlterField(
            model_name='card',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='story_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='column',
            name='color',
            field=models.CharField(default='#808080', max_length=7),
        ),
    ]
