# Generated by Django 5.0.6 on 2024-10-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_card_color_alter_card_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
