# Generated by Django 5.0.6 on 2024-10-24 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_image'),
        ('core', '0007_alter_board_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='column',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='column',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('board_id', models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.CASCADE, to='core.board')),
                ('card_id', models.ForeignKey(db_column='card_id', on_delete=django.db.models.deletion.CASCADE, to='core.card')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'unique_together': {('user_id', 'card_id', 'board_id')},
            },
        ),
    ]
