# Generated by Django 5.1.1 on 2024-10-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
